import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: {
          50: "#f7f5ff",
          100: "#f0ebff",
          200: "#e0d6ff",
          300: "#c7b3ff",
          400: "#a988ff",
          500: "#8a57ff", // Primordial Brand Purple
          600: "#752eff",
          700: "#6014fa",
          800: "#510fd1",
          900: "#440dae",
          950: "#270477",
        },
        accent: {
          pink: "#ff4d94",
          gold: "#e6b800",
          teal: "#00b3b3",
        },
        surface: "#f7f9ff",
        "secondary-container": "#fea520",
        "on-primary": "#ffffff",
        "on-surface": "#091d2e",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#ffb595",
        "surface-variant": "#d1e4fb",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#edf4ff",
        "on-secondary-fixed": "#2b1700",
        "tertiary-fixed": "#ffdad5",
        "on-background": "#091d2e",
        "secondary-fixed": "#ffddb9",
        "tertiary-fixed-dim": "#ffb4a9",
        "surface-container": "#e3efff",
        "on-surface-variant": "#594238",
        "surface-bright": "#f7f9ff",
        "secondary-fixed-dim": "#ffb961",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#ffb595",
        "surface-container-highest": "#d1e4fb",
        "primary": "#9e3d00",
        "secondary": "#865300",
        "on-primary-container": "#fffbff",
        "inverse-surface": "#203243",
        "on-primary-fixed": "#351000",
        "on-error": "#ffffff",
        "primary-fixed": "#ffdbcd",
        "primary-container": "#c64f00",
        "on-tertiary-container": "#fffbff",
        "tertiary": "#b1241a",
        "on-error-container": "#93000a",
        "surface-tint": "#a23f00",
        "error": "#ba1a1a",
        "background": "#f7f9ff",
        "surface-container-high": "#d9eaff",
        "error-container": "#ffdad6",
        "tertiary-container": "#d43e30",
        "surface-dim": "#c9dcf3",
        "on-secondary-fixed-variant": "#663e00",
        "outline-variant": "#e0c0b2",
        "outline": "#8c7166",
        "inverse-on-surface": "#e8f2ff",
        "on-tertiary-fixed-variant": "#910807",
        "on-secondary-container": "#694000",
        "on-primary-fixed-variant": "#7c2e00",
        "on-tertiary-fixed": "#410000"
      },
      borderRadius: {
        'brand-sm': '0.375rem',
        'brand-md': '0.75rem',
        'brand-lg': '1.25rem',
        'brand-xl': '2rem',
        'DEFAULT': "0.25rem",
        'lg': "0.5rem",
        'xl': "0.75rem",
        'full': "9999px"
      },
      spacing: {
        'xs': "4px",
        'base': "8px",
        'md': "24px",
        'lg': "48px",
        'sm': "12px",
        'xl': "80px",
        'container-max': "1280px",
        'gutter': "20px"
      },
      fontFamily: {
        "headline-md": ["Be Vietnam Pro"],
        "body-lg": ["Be Vietnam Pro"],
        "headline-sm": ["Be Vietnam Pro"],
        "display-lg-mobile": ["Be Vietnam Pro"],
        "label-md": ["Be Vietnam Pro"],
        "display-lg": ["Be Vietnam Pro"],
        "label-sm": ["Be Vietnam Pro"],
        "body-md": ["Be Vietnam Pro"]
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      },
      animation: {
        fadeIn: "fadeIn 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        slideUp: "slideUp 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        slideRight: "slideRight 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        shimmer: "shimmer 2s infinite linear",
        float: "float 6s ease-in-out infinite",
        pulseSubtle: "pulseSubtle 2s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(15px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        slideRight: {
          "0%": { transform: "translateX(-20px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        pulseSubtle: {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.85", transform: "scale(1.02)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
